### ISSUE TITLE
Alternative Linux Icon option is broken on Firefox

### ISSUE THREAD

**Issue by hjri** [jshackles/Enhanced_Steam#1570]
Seems to be that there are two styles loaded (enhancedsteam.css and enhancedsteam-firefox.css or something like that) and one is overriding the other. Option does work well on Chromium though, however there's a bug that icon reverts to steamos icon on hover in list.

**Comment by thomas-ashcraft** [comment]
Also Firefox trying to get images through moz-extenstion protocol. Like:
> moz-extension://steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png
```CSS
span.platform_img.steamplay {
	width: 72px;
	background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_steamplay.png' );
}

span.platform_img.win {
	background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_platform_win.png' );
}

span.platform_img.mac {
	background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_platform_mac.png' );
}

span.platform_img.linux {
	background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png' );
}
```

Since in that month (april 2018) Valve switched web content to using https, I think its ok to specify https:// in the urls, like in that case.

P.S. Some official clues about Valve going to https:
https://steamcommunity.com/groups/SteamClientBeta/discussions/1/1696043806558039623/#c1696043806558423700
