### ISSUE TITLE
[Suggestion] Replace the Linux platform icon.

### ISSUE THREAD

**Issue by beardedlinuxgeek** [jshackles/Enhanced_Steam#734]
Change the SteamOS icon back to a Tux icon. The SteamOS icon is confusing and there's no tooltip to suggest that it means Linux. I thought it was just related to SteamPlay. It wasn't until I looked at the css class on the icon that I knew it meant the game was playable on Linux.

Here's the CSS I'm using with the Stylish browser extension:
```css
span.platform_img.linux {
    background-image: url(http://i.imgur.com/mKIQhK8.png?1);
}
```
